# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: false
        cookie_samesite: lax
        cookie_httponly: false
        cookie_lifetime: 3600

    php_errors:
        log: true

when@test:
    framework:
        test: true
        # Commenté pour permettre les vraies sessions dans les tests fonctionnels
        # session:
        #     storage_factory_id: session.storage.factory.mock_file
